### ISSUE TITLE
Factorize code for creating a default RO with a mesh

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#101]
Lots of time across the engine, there's a common piece of code to create a render object with default values from a mesh. This could be made into a function or a factory method.

It's a general version of #81.

**Comment by Zouch** [comment]
There is already one method for this in RenderObject.cpp, `createRenderObject`.

**Comment by Zouch** [comment]
I added a factory from an asset, plus a more general factory.
