### ISSUE TITLE
Z check when displaying gizmos

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#105]
Gizmo displayed have no z order, just draw order.

**Comment by louen** [comment]
related to #46

**Comment by louen** [comment]
![noznogain](https://cloud.githubusercontent.com/assets/1011507/16649618/08981cd2-443a-11e6-912b-696f5ffc9bd1.png)

**Comment by Zouch** [comment]
Fixed by commit 7b4554c
