### ISSUE TITLE
Use Cmake's External project for assimp

### ISSUE THREAD

**Issue by AgatheD** [AGGA-IRIT/Radium-Engine#106]
To avoid long and useless compilation time...

**Comment by louen** [comment]
http://stackoverflow.com/questions/38123948/build-external-library-only-once-with-cmake

**Comment by Zarzwick** [comment]
Sorry for the loooooong delay. So here is a **partial** solution to the use of ExternalProject.

Partial means that for now it seemingly doesn't support compiling assimp in debug mode (this is why the if in main `CMakeLists.txt` are commented out)

Apart of that the solution seems quite good as we don't re-download assimp. The lib is **still a submodule**.

**Comment by Zouch** [comment]
Compiling assimp just once in release mode is perfectly fine as long as it links properly on debug. We should not need to (or at least have to) debug assimp code.

**Comment by louen** [comment]
Can anyone confirm me that it works, and I'll close the issue.

**Comment by Zouch** [comment]
I launched the compilation from scratch on windows, I tell you tomorrow.

**Comment by Zouch** [comment]
There is a problem with the pbd's on debug on windows (cmake can't find it for the install step), this needs some investigation (and a better fix than just the INSTALL "" for MSVC :D )

**Comment by louen** [comment]
It seems that when you build in Debug first on MSVC it still configures the radium libs to link against the release version of assimp (which is not there)

**Comment by nmellado** [comment]
Status: external build is working partially. The output directory is not ok with the update on the build system. This causes compilation and run issues on Mac (not tested for windows).
Should be able to fix this soon.

**Comment by louen** [comment]
I consider this issue fixed by #176
