### ISSUE TITLE
Upgrade Eigen to 3.3

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#108]
Newer versions of GCC (6.x) actually enforced the deletion of deprecated functions of C++11 that are in eigen.

Eigen removed these functions in newer versions.

We must update Eigen, and check that everything works fine.

**Comment by Zarzwick** [comment]
How could I test it ? Just downloading the latest version from github and replace the files would work ?

**Comment by louen** [comment]
I'm taking care of it. Shh it'll be over soon :)

**Comment by louen** [comment]
Please report any bug with eigen 3.2.8 by reopening this issue

**Comment by Zouch** [comment]
Actually, it seems that updating to 3.2.8 did not fix the issues since they are fixed in 3.3 (which is still in beta).
Maybe we could try to update to 3.3 in a test branch and check that we don't encounter bugs.

**Comment by louen** [comment]
Hmm. I'm not really in favor to using something as critical as eigen which has not been "blessed" by the release team, especially since we can just work around it for now.

**Comment by louen** [comment]
Eigen 3.3 is out !

**Comment by louen** [comment]
There's the eigen_33 branch which should work.
Can anyone with linux and macos confirm that it works ?

**Comment by Zouch** [comment]
Rendering in double precision is working properly on linux. Did not test stuff in animation related plugins, but I guess it should be fine.

**Comment by louen** [comment]
Eigen 3.3.0 merged. Please reopen this issue if anything goes bad
