### ISSUE TITLE
Gizmos not working at all (not being even displayed)

### ISSUE THREAD

**Issue by mauriziokovacic** [AGGA-IRIT/Radium-Engine#119]
Doesn't matter what I pick through the mouse interaction or through the UI, the gizmos are not even showing up

**Comment by louen** [comment]
You need to click on the buttons, man.

**Comment by mauriziokovacic** [comment]
Yes I remember how they works :P 
It's only that I can click even with a hammer those buttons that nothing is displayed anyway

**Comment by louen** [comment]
Is this still relevant ? I had no problem  with the gizmos on any version.

**Comment by Zouch** [comment]
Actually this is still relevant, I can't get the gizmos to show up.
Since you closed the issue @mauriziokovacic, what was causing the problem ?

**Comment by Zouch** [comment]
Looks like I was not selecting an entity.
