### ISSUE TITLE
Limit openGL functions to core profile

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#124]
According to @MathiasPaulin : if we want to be compatible with MacOS, we need to restrict the set of openGL functions to openGL3 core and not use other deprecated functions.

This problem is hard to see on Windows (because of GLEW) and on Linux because it doesn't use the core profile by default.

**Comment by Zouch** [comment]
#131

**Comment by nmellado** [comment]
Seems to be fixed by 62e1712fb1d633f6ab14b953c89e0c6b6b6ecc95. 
Someone confirms ?

**Comment by louen** [comment]
@MathiasPaulin  I think @nmellado  meant you.

**Comment by nmellado** [comment]
This seems to be fixed with PR #195 and previous.
Closing.
