### ISSUE TITLE
Replace crappy keyboard event polling by clearer and more efficient event handling.

### ISSUE THREAD

**Issue by MathiasPaulin** [AGGA-IRIT/Radium-Engine#129]
Function isKeyPressed (Keyboard.hpp/.cpp) and its implementations on both Linux and MacosX is a pain on the ass for both coding style (very poor event handling approach) and performances (7 connexion to X server at each frame are opened/closed on Linux, require using a deprecated low level library on MacOs or big ObjectiveC glue).
This function is rarely used and must be replaced by proper Qt keyboard event handling on the appropriate QObject.

**Comment by Zouch** [comment]
This should now be more or less free (a simple map access) to check wether a key is pressed or not. 

I still think this can be useful to be able to perform this simple check at any time without having to deal with all the qt stuff or keep member variables up to date everywhere this behaviour is needed.
