### ISSUE TITLE
Eigen as submodule

### ISSUE THREAD

**Issue by nmellado** [AGGA-IRIT/Radium-Engine#146]
Would be nice, using hg-git: http://hg-git.github.io/
So we don't need to package eigen directly in the source code, we can track their devel branch, ....

Exists as package in your favorite linux distro (https://packages.debian.org/sid/vcs/mercurial-git), but a bit more work is required for windows users (https://github.com/cosmin/git-hg#dependencies)
-> considering multi-plateform support, not sure it is the best solution. What do you think ?

**Comment by louen** [comment]
we could use this , as suggested by charly :  https://github.com/RLovelett/eigen

**Comment by nmellado** [comment]
Sounds good.

**Comment by nmellado** [comment]
Do we agree to restrict on the latest release branch ?
https://github.com/RLovelett/eigen/tree/branches/3.3

**Comment by nmellado** [comment]
Fixed by 62e1712fb1d633f6ab14b953c89e0c6b6b6ecc95. Closing
