### ISSUE TITLE
Automatically generate subtrees for Visual Studio

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#15]
Take a look at CMakeGenerateTrees.txt, it is fully handmade. Maybe we could find a way to generate those subtrees in a more automatic way.

**Comment by louen** [comment]
https://cmake.org/cmake/help/v3.0/command/source_group.html

**Comment by nmellado** [comment]
This issue seems obsolete. Do you confirm ?

**Comment by louen** [comment]
Well it's kind of a "we will  do it when someone bothers"...

**Comment by nmellado** [comment]
As far as I see, `CMakeGenerateTrees.txt` doesn't exist anymore.
What was the purpose of this file ?
The solution today generated by cmake seems good to me.

**Comment by louen** [comment]
The idea was to have the folder hierarchy mirrored in the file hierarchy of VS instead of having all files at the same level in each project.

**Comment by nmellado** [comment]
I see, fair enough. Sill open though :)

**Comment by louen** [comment]
This could be fixed in VS 2017 which I've heard supports CMake natively

**Comment by nmellado** [comment]
Ok. Todo then.

**Comment by nmellado** [comment]
We be fixed by WIP on branch [fixMVSC](https://github.com/AGGA-IRIT/Radium-Engine/tree/fixMVSC).

**Comment by nmellado** [comment]
This is currently fixed by PR #195.
