### ISSUE TITLE
Clear the Engine

### ISSUE THREAD

**Issue by hoshiryu** [AGGA-IRIT/Radium-Engine#154]
It would be nice to have a clean way to clear the Engine.
For example, if one wants to reset the Engine without having to relaunch the app (like a "new scene") or reload a complete scene.
Thus, destruction signals have to be managed correctly ( see issue #153 ), as for the component unregistration from the systems.

**Comment by louen** [comment]
As I said to @hoshiryu , the implementation of this function should be nothing but removing all entities from the engine, and leave the destruction order handle resource deletion  correctly.
