### ISSUE TITLE
Renderer rewriting --> Renderer milestone ?

### ISSUE THREAD

**Issue by MathiasPaulin** [AGGA-IRIT/Radium-Engine#156]
This is the first post of the road map for rewriting the renderer. 
@louen perhaps you must create a milestone Renderer-Storm (or something like that) to identify easily all feature requests and other comments on the refactoring/rewriting of the renderer.
Fell free to express yourself.
The work (experimental from now to mid april) will start on branch expe-mathias.
In a first time, we will keep the Renderer interface and rewrite all the openGL stuff. (before summer)
In a second time, we will propose a new renderer interface (in the summer).

On objective of this rewriting is to make rendering development more efficient and suppress the maintenance by the team of the low level interface. But we want to keep the hability to work at low level. Thats why we do not plug Unreal Engine (or others) to the Radium.

I'll manage the renderer development from now until it is mature enough to be merged with master.

cheers.

**Comment by louen** [comment]
Done
