### ISSUE TITLE
Keyboard management

### ISSUE THREAD

**Issue by Jeckhys** [AGGA-IRIT/Radium-Engine#186]
I implemented a keymapping system in my branch (ab89e569938d59f1cb4984ba62c59c1c36763d1f) inspired by the way Keyboard.cpp/hpp was implemented.

So it's not a class, it just contains namespace functions and I would like to know if it would be better to create a singleton class for both keymapping and keyboard cpp/hpp instead of the actual implementation ?

**Comment by louen** [comment]
If it doesn't have a state (i.e. member variables) why should it be a class ?
