### ISSUE TITLE
Fix renderer switching in MainApplication

### ISSUE THREAD

**Issue by Jeckhys** [AGGA-IRIT/Radium-Engine#187]
I implemented a new renderer (the PhotoStudio one), but it's not yet possible to switch between renderers using the MainApp's combobox. I saw a lot of commented functions about this (in Viewer class and MainApp) but it seemed to be buggy when I uncommented them..

Have you got an idea about how we could handle renderer switching correctly ?

**Comment by louen** [comment]
Is this related to #216  ?

**Comment by nmellado** [comment]
Yes. this two issues are the same.
I'm closing this one.
