### ISSUE TITLE
Test and fix camera

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#19]
It looks like there is a bug in the camera : 
When I rotate the camera around a target point (trackball class), it's all ok, but, if I change the target point via the UI, and then rotate the camera again, the camera target is plenty of crap.
Might be worth checking
* TrackballCamera::setTargetPoint()
* TrackballCamera::handleCameraRotate()
* Camera::setTargetPoint
* Camera::transform

**Comment by louen** [comment]
Camera now seems to be OK but needs more testing

**Comment by louen** [comment]
We need to keep the axis constrained in the trackball camera, and maybe add a free-flying camera as welll.

**Comment by louen** [comment]
Camera doesn't work when no scene is loaded. Fix it Charly ! :)

**Comment by Zouch** [comment]
I can't remember when, but I think I fixed this. Reopen this issue it if I'm wrong.
