### ISSUE TITLE
New build system fails on Windows

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#192]
The addition of glbindings and changes to the build system introduced by #176 have broken the build on windows

## Build-breaking issues
* Incorrect linking libraries (release build linked with debug libraries)
* Incorrect suffix handling for glbinding (library generated with suffix e.g. `glbindings-vc130-mt.lib`) while linker attempts to link with `glbindings.lib`)

## Runtime issues
* Programs crashes when attempting to read the context strings of glbindings. Might be related to library linking with different std libs.

**Comment by MathiasPaulin** [comment]
I'll give a look but I've no way to get access to a window system... When writing this part, I just copy the lines from assimp stuff. I'll modify some stuff, blindly, in my PR fixBuildSystem

**Comment by nmellado** [comment]
I'm on this issue. I've been working on this for several days now.
I'm just waiting the build chain is stabilized to update and PR my changes.

The integration with VS 2017 is much easier now, cmake is processed directly by VS, which solves a lot of problems.

**Comment by nmellado** [comment]
WIP on branch [fixMVSC](https://github.com/AGGA-IRIT/Radium-Engine/tree/fixMVSC).

**Comment by nmellado** [comment]
See PR #195
