### ISSUE TITLE
acecpted pull request Show/hide gizmos instead of delete/creating them break simple app test0

### ISSUE THREAD

**Issue by MathiasPaulin** [AGGA-IRIT/Radium-Engine#194]
The compilation is OK, but, the change in the constructor of the gizmo manager (file  src/GuiBase/Viewer/Gizmo/GizmoManager.cpp, adding the creation of several gizmos (Translate, Rotate, nullptr) make the application test0 segfault.

When creating such gizmos, the call Engine::SystemEntity::uiCmp() try to get the instance of the singleton SystemEntity that is not yet created (and then equals to nullptr) when this is called by the simple app test0. So ... the results is ... BAD_ACCESS --> SEGFAULT.
Authors of pull request MUST test the 2 example applications and all the "standard" plugins in each build type : Debug, RelWithDebInfo, Release before submitting pull request. While waiting for a working continuous integration procedure (OK, not tomorrow), reviewers of pull request must also verify this on their system!!!

I'll try to fix this in the frame my fixBuildSystem pull request (even if thes are two different things) , so, wait a few before validating it.

**Comment by louen** [comment]
This is why we need continuous integration :)

**Comment by MathiasPaulin** [comment]
Yep, this is mentioned that in my message ... But thereis several technical problems for that. it's on the road but ... not tomorrow as I said.

**Comment by nmellado** [comment]
Test0 does not crash anymore on VS.
Is this fixed ?

**Comment by louen** [comment]
Can we close this issue ?

**Comment by hoshiryu** [comment]
Ping: is this issue still topical?

**Comment by nmellado** [comment]
@MathiasPaulin , what do you think ?

**Comment by MathiasPaulin** [comment]
we can close this issue.
