### ISSUE TITLE
Command line /  config options

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#22]
* log level | logfile etc. 
* max fps
* enable/disable timers

**Comment by louen** [comment]
http://doc.qt.io/qt-5/qcommandlineparser.html

**Comment by Zouch** [comment]
Max FPS is already configurable (--fps value)
Other stuff could be done easily. (Smarter parsing could be done though)

**Comment by louen** [comment]
@Zouch  : can I close this one ?

**Comment by Zouch** [comment]
Yep

2016-04-11 16:56 GMT+02:00 Valentin Roussellet <notifications@github.com>:

**Comment by louen** [comment]
fixed in 05c3a1
