### ISSUE TITLE
DLL_IMPORTs

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#43]
All the 
```
#if defined RA_XXX_EXPORTS
#  define RA_XXX_API DLL_EXPORT
#elif defined RA_XXX_IMPORTS
#  define RA_XXX_API DLL_IMPORT
#else
#  define RA_XXX_API
#endif
```
should be moved to 
```
#if defined RA_XXX_EXPORTS
#  define RA_XXX_API DLL_EXPORT
#else
#  define RA_XXX_API DLL_IMPORT
#endif
```
since we cannot ask the plugins / application developers to define this macro (and if you are a library user you will need the `DLL_IMPORT` anyways)

**Comment by louen** [comment]
I agree to do that for plugins since they are always going to be dlls.
But for radium libs, we might wanna compile them as static lib for some reason, so there needs to be an option for neither dllimport nor dllexport
