### ISSUE TITLE
Animation::Handle::getLabel crashes

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#54]
Commit #509f90e introduced a crash when right clicking a bone.
The method Animation::Handle::getLabel tries to access element m_label[0] but m_label is empty.

**Comment by louen** [comment]
@0xg  : could you make it so that the loading code forces labels to the bones ? (by auto-naming them if they are not named ) ?

**Comment by 0xg** [comment]
@louen It should be working now.
