### ISSUE TITLE
Correct mesh (memory) handling

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#55]
When cloning render object, the mesh is also cloned. 
But the render objects never free the meshes memory, so there is a memory leak there.
The problem is, for now, we cannot really safely delete a mesh (and it's vbos) since they might be shared (because of cloning mechanics).

So we must find a smarter way to handle meshes safe duplication and release (smart pointers, asset manager, etc)

**Comment by louen** [comment]
0f3796cab removed cloning mesh, so closing this one
