### ISSUE TITLE
Improve the loading process

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#58]
* pass the aiScene as the common interchange format

**Comment by Zouch** [comment]
I don't agree. At least for long term stuff.
We need to parse the given file only once, and store all loaded data in an asset manager. Then we tell the plugins "Ok, some new data has been loaded, you will find it in the asset manager, do whatever you want with it"

**Comment by louen** [comment]
whynot use the aiScene as our asset manager then ?

**Comment by Zouch** [comment]
We will still need to keep on parsing the file over and over.
Plus, some data might not come from assimp (ie physics data and so on)

**Comment by Zouch** [comment]
Loaded files are now processed just once and Core data is given to systems for creation. I think we can consider this issue as fixed.
