### ISSUE TITLE
Render objects double buffer rework

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#68]
Commit 8c28b15 removed (not in the most elegant way...) double buffering for render objects. This might need to be tested (e.g. keep sure to not update stuff multiple times, etc)

Using locks might be needed if weird rendering bugs occur when modifying the geometry for example.

**Comment by louen** [comment]
See also #55

**Comment by louen** [comment]
Commit 0f3796cab removed it
