### ISSUE TITLE
Performance loss between radium and radium v2

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#69]
These two screenshots show the difference between an empty scene in radium v1 and v2.

![radium_v1](https://cloud.githubusercontent.com/assets/1011507/13055091/a3e4d2c2-d40d-11e5-899d-18d8dde46177.png)
![radium_v2](https://cloud.githubusercontent.com/assets/1011507/13055094/a54a8012-d40d-11e5-8cc7-f6c2bafa1613.png)

We need to figure out why there was a 3x slowdown in "frame" timers.

**Comment by louen** [comment]
Did you remove the useless keyboard stuff ?

**Comment by Zouch** [comment]
The code is there but not called, we can remove the whole function though

**Comment by louen** [comment]
![make-it-so-captain](https://cloud.githubusercontent.com/assets/1011507/19410310/13db4e22-92e9-11e6-885d-a434fe88f529.jpg)
