### ISSUE TITLE
Build application in separate project than engine libs

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#70]
Allow for better granularity of dependencies and decoupling.

**Comment by Zouch** [comment]
Ok, so actually there are some "application commons", like TimerData or PluginBase stuff, that are app or Qt related. What do we wanna do with it?

**Comment by Zarzwick** [comment]
What I need to do is to build the core and engine as a standalone library and build the application (MainApplication or whatever is specific to Radium) on the top of it, is that correct ?

**Comment by Zarzwick** [comment]
I also could (and will for painty project) modify the CMakeLists.txt to make it compilable from a higher-level directory (if Radium is included as a submodule, for example)

**Comment by Zarzwick** [comment]
Now the MainApplication has its own directory **on the project root**.

What `src/` contains now is everything related to the libs. Some classes moved there (`GuiBase`):
+ `PluginBase`
+ `Viewer`
+ `Utils/Keyboard`
