### ISSUE TITLE
Tidy up shaders and rendering methods

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#78]
- [x] Shaders should share common code if possible
- [x] Shaders should work or fail gracefully
- [x] We miss a "wireframe only" shader, and a proper "flat" shader as well

**Comment by Zouch** [comment]
First point is actually easy to do by just enabling the fact that a shader
is not Name.frag.glsl Name.vert.glsl, etc but a vertex shader
"foo.vert.glsl", a frag "bar.frag.glsl", etc.
Refactor on the shaders need to be done anyways.

2016-02-25 19:47 GMT+01:00 Valentin Roussellet <notifications@github.com>:

**Comment by MathiasPaulin** [comment]
I’am working on this kind of stuff for VortexEngine and David will have a student from april to june to work also on that …
We’ll discus of all rendering related stuff as soon as I’m back to Toulouse. (The other question about BVH, kdtree and son on is also to be discussed. Vortex engine has a raytracer that use optimal KdTree ….)

Cheers,
--
Mathias PAULIN           http://www.irit.fr/~Mathias.Paulin
IRIT-Université de Toulouse                               FRANCE

**Comment by Zouch** [comment]
* Hugo has done / is doing stuff on the second point, should be fixed soon. 
 * There is now a "wireframe only" mode (everything is wireframe though)

**Comment by louen** [comment]
c183403 solves problem number 2

**Comment by louen** [comment]
Wireframe mode by pressing Z solves issue #3.

**Comment by Zouch** [comment]
Encore une victoire de canard !

2016-06-02 16:45 GMT+02:00 Valentin Roussellet <notifications@github.com>:
