### ISSUE TITLE
Detaching and reattaching side dock creates black screen

### ISSUE THREAD

**Issue by louen** [AGGA-IRIT/Radium-Engine#82]
Repro :
Detach the side dock
reattach it.
Screen is black.

**Comment by louen** [comment]
Only repros on my screen it seems

**Comment by louen** [comment]
This appears to repro only if you have KDE. Weird

**Comment by Zouch** [comment]
Still relevant ?

**Comment by louen** [comment]
I changed my window manager, so I think we can close it since even I cannot reproduce it anymore...

**Comment by Zarzwick** [comment]
Since I'm still on KDE (Qt 5.7) I just checked with latest build and everything seem to work correctly. Changing side is supported, independant window works too and simple drag-and-drop doesn't make a black screen.

**Comment by Zouch** [comment]
Thanks for the input, I close the issue then :)
