### ISSUE TITLE
Separate debug and release builds to improve compile times when switching

### ISSUE THREAD

**Issue by Zouch** [AGGA-IRIT/Radium-Engine#93]
Ok, basically there are two ways to deal with that, both can be done via cmake : 
- Having two output directories (say {build, bin}-{deb|rel})
- Having a postfix for debug targets (radiumCored, radiumEngined, radiumd)

The main drawback with the first point is the need to have dlls on both bin directories, but there is a clear separation between both compilations (which is maybe the main problem of the second point).

Any suggestion ?

**Comment by Zouch** [comment]
It looks like, on MSVC, generated objects are separated per build config, and, with single-config build systems (like Makefile), this is not something that is doable automagically. 
Hence, I guess the best thing is to use different build directories (and have an IDE or a script manage this for us).

After a bit of testing, separating the output files (libs / bins) is not really relevant, since the link time for them is really not an issue. I guess we can close this issue.

**Comment by louen** [comment]
We must have separate plugins folders for builds, unfortunately. Or filters to load only debug/release plugins.

**Comment by nmellado** [comment]
We can still configure cmake to use different directories in debug and release modes (http://stackoverflow.com/a/20835044). So we have one single build dir (from which you call cmake), an several folders generated depending on th build type.

This is very simple to do. Maybe I'm missing something with this request.

**Comment by Zouch** [comment]
Well actually there are two issues that are a bit mixed there.

The first one is "it could be great to be able to avoid having to recompile everything when changing build type". Since `make` is not able to handle different configurations, avoiding this means building in different directories.

The second issue is more related the the plugins. It appears that there are some problems with plugins that are not recompiled when changing the main application build type (if I understood correctly what Valentin meant) thus leading runtime problems.
This one could / should be handled by outputing the dlls to a different folder, depending on the build type (maybe just append `-dbg` or `d` to the debug output directory)

**Comment by nmellado** [comment]
Right, I agree with that. 
I'm thinking about a fix, I will try to push it by the end o th week.

**Comment by louen** [comment]
Fixed by PR #151
